import { AlertCircle, Bot } from "lucide-react";

export interface AuthorInfoProps {
  /** When the content was last updated */
  lastUpdated: Date | string;
  /** Type of content - affects the message */
  contentType?: "cluster" | "qa" | "video" | "custom";
  /** Custom CSS class name */
  className?: string;
}

/**
 * AuthorInfo component displays AI-generated content disclosure
 * Shows "AI-Generated Content" message, last updated date, and disclaimer
 *
 * Important for transparency, user trust, and Google's E-E-A-T guidelines
 */
export function AuthorInfo({
  lastUpdated,
  contentType = "cluster",
  className = "",
}: AuthorInfoProps) {
  const dateObj =
    typeof lastUpdated === "string" ? new Date(lastUpdated) : lastUpdated;

  // Format relative time
  const now = new Date();
  const diffMs = now.getTime() - dateObj.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  let displayText: string;
  if (diffDays === 0) {
    displayText = "today";
  } else if (diffDays === 1) {
    displayText = "yesterday";
  } else if (diffDays < 7) {
    displayText = `${diffDays} days ago`;
  } else if (diffDays < 30) {
    const weeks = Math.floor(diffDays / 7);
    displayText = `${weeks} ${weeks === 1 ? "week" : "weeks"} ago`;
  } else {
    displayText = dateObj.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  }

  const messages = {
    cluster:
      "This article was generated by AI using RAG (Retrieval-Augmented Generation) from authoritative sources.",
    qa: "This answer was generated by AI using verified information from multiple sources.",
    video:
      "Video metadata and transcript were automatically processed and ingested.",
    custom: "This content was generated by AI from real user questions.",
  };

  return (
    <div
      className={`rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 ${className}`}
    >
      <div className="flex items-start gap-3">
        <Bot className="h-5 w-5 shrink-0 text-amber-400" />
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className="text-sm font-semibold text-amber-200">
              AI-Generated Content
            </span>
            <span className="text-xs text-white/40">•</span>
            <time
              dateTime={dateObj.toISOString()}
              className="text-xs text-white/50"
              title={dateObj.toLocaleString()}
            >
              Updated {displayText}
            </time>
          </div>
          <p className="mt-1 text-xs text-white/60">{messages[contentType]}</p>
          <div className="mt-2 flex items-start gap-1.5 text-[11px] text-amber-200/60">
            <AlertCircle className="h-3 w-3 shrink-0 mt-0.5" />
            <span>
              While we strive for accuracy, AI-generated content may contain
              errors or outdated information. Always verify important facts from
              primary sources.
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
